### ISSUE TITLE
Pytest standalone for distutils

### ISSUE THREAD

**Issue by paulmueller** [cimatosa/jobmanager#10]
I would like to integrate pytest into the package and create a "runtests.py" into the test directory.
http://pytest.org/latest/goodpractises.html#create-a-pytest-standalone-script
This is more convenient as I experienced problems running pytest in a virtualenv with python-pytest installed on debian. We will also be able to do 

    python setup.py test

Moreover I would like to move the run_pytest_html.sh into the test directory, because I believe it belongs there.

I will do all these things if there are no objections @cimatosa 

Cheers,
Paul

**Comment by cimatosa** [comment]
sure go ahead
