### ISSUE TITLE
client function call returns None

### ISSUE THREAD

**Issue by cimatosa** [cimatosa/jobmanager#30]
hey I think there is something missing here:
https://github.com/cimatosa/jobmanager/blob/master/jobmanager/jobmanager.py#L342-344
this alternative call does not return anything!

**Comment by paulmueller** [comment]
It certainly seems to be the case. It looks like `func` is never called when `count_args != ["c", "m"]`. This would actually break a lot of my code, so I must have overlooked something.
I will have a look at the `wrapper_example.py`. It is currently not working as-is.
